title: Mesafesiz Sohbetler
description: Mesafesiz Sohbetler'e Hoşgeldiniz! Aşağıdaki kısma şifreyi giriniz.
theme: jekyll-theme-cayman
google_analytics:
meeting_link: https://meet.jit.si/Mesafesiz%20Sohbetler-EO55aLN9otOI#jitsi_meet_external_api_id=0&amp;config.getroomnode=undefined&amp;interfaceConfig.APP_NAME=%22Mesafesiz%20Sohbetler%22&amp;interfaceConfig.DEFAULT_REMOTE_DISPLAY_NAME=%22Kat%C4%B1l%C4%B1mc%C4%B1%22&amp;interfaceConfig.TOOLBAR_BUTTONS=%5B%22microphone%22%2C%22camera%22%2C%22fullscreen%22%2C%22info%22%2C%22chat%22%2C%22settings%22%2C%22raisehand%22%2C%22videoquality%22%2C%22videobackgroundblur%22%5D&amp;interfaceConfig.SETTINGS_SECTIONS=%5B%22microphone%22%2C%22camera%22%2C%22fullscreen%22%2C%22info%22%2C%22chat%22%2C%22settings%22%2C%22raisehand%22%2C%22videoquality%22%2C%22videobackgroundblur%22%5D&amp;interfaceConfig.SHOW_JITSI_WATERMARK=false&amp;interfaceConfig.SHOW_WATERMARK_FOR_GUESTS=false&amp;interfaceConfig.filmStripOnly=false
course_activated: true
show_links: false
show_mainpage_button: true
