title: BlockLearn Course Page Boilerplate
description: Create your own course page with live meeting feature in minutes
theme: jekyll-theme-cayman
google_analytics:
meeting_link: https://meet.jit.si/Blocklearn-4YR4aBi4jvwT#jitsi_meet_external_api_id=0&amp;config.getroomnode=undefined&amp;interfaceConfig.APP_NAME=%22Blocklearn%22&amp;interfaceConfig.DEFAULT_REMOTE_DISPLAY_NAME=%22Fellow%20Learner%22&amp;interfaceConfig.TOOLBAR_BUTTONS=%5B%22microphone%22%2C%22camera%22%2C%22fullscreen%22%2C%22chat%22%2C%22settings%22%2C%22raisehand%22%2C%22videoquality%22%2C%22videobackgroundblur%22%5D&amp;interfaceConfig.SETTINGS_SECTIONS=%5B%22microphone%22%2C%22camera%22%2C%22fullscreen%22%2C%22chat%22%2C%22settings%22%2C%22raisehand%22%2C%22videoquality%22%2C%22videobackgroundblur%22%5D&amp;interfaceConfig.SHOW_JITSI_WATERMARK=false&amp;interfaceConfig.SHOW_WATERMARK_FOR_GUESTS=false&amp;interfaceConfig.filmStripOnly=false
course_activated: true
show_links: false
show_mainpage_button: true
